;PROBLEM 1 REVERSE GENERAL
(define (reverse-general L)
    (if (null? L)
        '()
        (if (list? (car L))
            (append (reverse-general (cdr L))
                (list (reverse-general (car L))))  
            (append (reverse-general (cdr L)) (list (car L)))
        )
    )
)

(display (reverse-general '()))
(newline)
(display (reverse-general '(1 2)))
(newline)
(display (reverse-general '(1 2 3)))
(newline)
(display (reverse-general '((a b c) (d e f))))
(newline)