;PROBLEM 1 REVERSE GENERAL
(define (reverse-general L)
    (if (null? L)
        '()
        (if (list? (car L))
            (append (reverse-general (cdr L))
                (list (reverse-general (car L))))  
        )
    )
)